const LABELS: Record<string, string> = {
  variables: "Переменные",
  data_types: "Типы данных",
  conditions: "Условия",
  conditionals: "Условия",
  loops: "Циклы",
  functions: "Функции",
  parameters: "Параметры функций",
  return_values: "Возврат результата",
  scope: "Область видимости",
  mutability: "Изменяемость данных",
  strings: "Строки",
  numbers: "Числа",
  booleans: "Логические значения",
  truthiness: "Проверка истинности",
  comprehensions: "Генераторы коллекций",
  lists: "Списки",
  tuples: "Кортежи",
  sets: "Множества",
  dictionaries: "Словари",
  slicing: "Срезы",
  iteration: "Перебор элементов",
  exceptions: "Исключения",
  try_except: "Обработка исключений",
  custom_exceptions: "Собственные исключения",
  modules: "Модули",
  packages: "Пакеты",
  imports: "Импорт",
  testing_basics: "Основы тестирования",
  assertions: "Проверки assert",
  pytest_basics: "Основы pytest",
  fixtures: "Фикстуры",
  typing_basics: "Основы типизации",
  type_hints: "Аннотации типов",
  dataclasses: "Классы данных",
  classes: "Классы",
  objects: "Объекты",
  inheritance: "Наследование",
  composition: "Композиция",
  protocols: "Протоколы",
  decorators: "Декораторы",
  generators: "Генераторы",
  iterators: "Итераторы",
  context_managers: "Контекстные менеджеры",
  http_basics: "Основы HTTP",
  rest: "Принципы REST",
  api_design: "Проектирование API",
  json: "Формат JSON",
  fastapi_basics: "Основы FastAPI",
  fastapi_routing: "Маршруты FastAPI",
  fastapi_dependencies: "Зависимости FastAPI",
  request_validation: "Проверка запросов",
  response_models: "Модели ответов",
  authentication: "Вход в систему",
  authorization: "Права доступа",
  sessions: "Пользовательские сессии",
  csrf: "Защита запросов",
  password_hashing: "Хранение паролей",
  async_python: "Асинхронный Python",
  async_io: "Асинхронный ввод и вывод",
  background_tasks: "Фоновые задачи",
  logging: "Логи приложения",
  configuration: "Настройки приложения",
  environment_variables: "Переменные окружения",
  error_handling: "Обработка ошибок",
  middleware: "Промежуточные обработчики",
  openapi: "Документация OpenAPI",
  websockets: "WebSocket",
  sql_basics: "Основы SQL",
  postgresql: "PostgreSQL",
  sql_select: "Выборка данных",
  sql_joins: "Объединение таблиц",
  sql_indexes: "Индексы",
  transactions: "Транзакции",
  isolation: "Изоляция транзакций",
  migrations: "Миграции базы данных",
  sqlalchemy_core: "SQLAlchemy Core",
  sqlalchemy_orm: "SQLAlchemy ORM",
  relationships: "Связи моделей",
  n_plus_one: "Проблема лишних запросов",
  connection_pooling: "Пул соединений",
  caching: "Кеширование",
  redis_basics: "Основы Redis",
  docker_basics: "Основы Docker",
  linux_cli: "Командная строка Linux",
  git_basics: "Основы Git",
  git_branching: "Ветки Git",
  ci_basics: "Автоматические проверки",
  ci_testing: "Тесты в CI",
  structured_logging: "Структурированные логи",
  observability: "Наблюдаемость",
  security_basics: "Основы безопасности",
};
export function skillLabel(id: string): string {
  return LABELS[id.split(".").at(-1) ?? ""] ?? "Тема курса";
}
