"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api, User } from "../lib/api";

type Question={id:string;skill_id:string;difficulty:number;prompt:string;choices:string[];question_number:number;total_questions:number};
type State={status:string;completed:boolean;score:number|null;answered:number;question:Question|null};
type Answer={correct:boolean;feedback:string;state:State};
export default function AssessmentPage(){
 const router=useRouter(); const [state,setState]=useState<State|null>(null); const [answer,setAnswer]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [restarting,setRestarting]=useState(false);
 useEffect(()=>{void (async()=>{try{const user=await api<User>("/me");if(!user.profile?.onboarding_completed){router.replace("/onboarding");return;}setState(await api<State>("/assessment"));}catch{router.replace("/auth");}})()},[router]);
 async function restart(){setRestarting(true);setError("");try{setState(await api<State>("/assessment/restart",{method:"POST"}));}catch(err){setError(err instanceof Error?err.message:"Не удалось начать диагностику");}finally{setRestarting(false);}}
 async function submit(e:FormEvent){e.preventDefault();if(!state?.question||busy)return;setBusy(true);setError("");try{const result=await api<Answer>("/assessment/answers",{method:"POST",body:JSON.stringify({question_id:state.question.id,answer})});setState(result.state);setAnswer("");}catch(err){setError(err instanceof Error?err.message:"Не удалось сохранить ответ");}finally{setBusy(false);}}
 return <main className="auth-shell"><header className="topbar"><a className="brand" href="/dashboard">AI-наставник<span className="brand-dot">.</span></a><a href="/dashboard">Дашборд</a></header><section className="auth-card"><span className="eyebrow"><i/> ДИАГНОСТИКА</span><h1>Определим точку старта.</h1><p className="auth-lead">Это короткая адаптивная проверка. Она не является экзаменом: следующий вопрос подстраивается по вашим ответам.</p>{error&&<p className="form-error" role="alert">{error}</p>}{!state&&<p role="status">Загружаем вопрос…</p>}{state?.completed?<><p role="status">Диагностика завершена. Результат: {Math.round((state.score??0)*100)}% правильных ответов.</p><p>Ответов сохранено: {state.answered}.</p><button className="primary-button" onClick={restart} disabled={restarting}>{restarting?"Готовим новую диагностику…":"Пройти диагностику ещё раз"}<span>↗</span></button><p><a href="/learning">Перейти к учебному пути →</a></p></>:state?.question&&<form onSubmit={submit}><p><strong>Вопрос {state.question.question_number} из {state.question.total_questions}</strong></p><h2>{state.question.prompt}</h2><fieldset disabled={busy}><legend>Выберите ответ</legend>{state.question.choices.map(choice=><label className="choice" key={choice}><input type="radio" name="assessment-answer" value={choice} checked={answer===choice} onChange={()=>setAnswer(choice)} required/>{choice}</label>)}</fieldset><button className="primary-button form-button" disabled={!answer||busy}>{busy?"Сохраняем…":"Ответить"}<span>↗</span></button></form>}</section></main>;
}
