"""Authored remaining Python and Backend skills; no learner code runs at import.

Examples explain a concept; the separate practice asks for a different result.
All answers, explanations and reference solutions are server-side content.
"""
from __future__ import annotations


def topic(skill, title, prerequisite, theory, example, output, question, choices,
          explanations, practice, solution, public, hidden, output_distractors,
          *, phase=None, minutes=20):
    lesson_id = skill.split(".", 1)[1].replace("_", "-") + "-v1"
    return dict(skill=skill, title=title, prerequisite=prerequisite, theory=theory,
                example=example, output=output, question=question, choices=choices,
                explanations=explanations, practice=practice, solution=solution,
                public=public, hidden=hidden, output_distractors=output_distractors,
                phase=phase, minutes=minutes, lesson_id=lesson_id)


TOPICS = [
    topic("python.dataclasses", "Dataclass: объект из объявленных полей", ["python.type_hints"],
          "Декоратор dataclass строит __init__, repr и сравнение по объявленным полям. Типы полей служат аннотациями; dataclass сам не валидирует ввод. Для изменяемого значения по умолчанию нужен field(default_factory=...), чтобы экземпляры не делили один контейнер.",
          "from dataclasses import dataclass\n@dataclass\nclass Price:\n    cents: int\nprint(Price(120) == Price(120))", "True",
          "Как дать каждому экземпляру свой пустой список?",
          ["Использовать field(default_factory=list)", "Записать общий список в атрибут класса", "Передать один список всем экземплярам"],
          ["Фабрика вызывается для каждого нового объекта.", "Атрибут класса разделяется экземплярами.", "Один переданный объект останется общей ссылкой."],
          "Реализуйте solve(payload): объявите dataclass Line с полями price:int и quantity:int, создайте его из payload и верните словарь {'total':price*quantity,'label':'Line'}. Цены и количество — неотрицательные целые; нулевое количество допустимо.",
          "from dataclasses import dataclass\n@dataclass\nclass Line:\n    price: int\n    quantity: int\ndef solve(payload):\n    line = Line(**payload)\n    return {'total': line.price * line.quantity, 'label': type(line).__name__}",
          [({"price": 7, "quantity": 3}, {"total": 21, "label": "Line"})],
          [({"price": 0, "quantity": 9}, {"total": 0, "label": "Line"}), ({"price": 20, "quantity": 0}, {"total": 0, "label": "Line"})], ["False", "Price(120)"], minutes=22),
    topic("python.classes", "Класс и инициализация экземпляра", ["python.dataclasses"],
          "Класс описывает состояние и методы. Вызов класса обычно создаёт экземпляр и затем вызывает __init__. Метод получает экземпляр в self; __init__ заполняет состояние и возвращает None. Возврат числа из __init__ является ошибкой.",
          "class Counter:\n    def __init__(self, value):\n        self.value = value\n    def increment(self):\n        self.value += 1\nc = Counter(4)\nc.increment()\nprint(c.value)", "5",
          "Для чего нужен self в методе экземпляра?", ["Чтобы обращаться к состоянию этого экземпляра", "Чтобы хранить имя файла класса", "Чтобы автоматически создать второй объект"],
          ["self связывает вызов метода с конкретным объектом.", "Имя файла не передаётся через self.", "Метод не обязан создавать новый объект."],
          "Напишите solve(payload): создайте класс Counter, начальное значение payload['start']; метод add(delta) меняет его значение. Примените все payload['deltas'] по порядку и верните итоговое целое. Пустой список изменений сохраняет start.",
          "class Counter:\n    def __init__(self, value): self.value = value\n    def add(self, delta): self.value += delta\ndef solve(payload):\n    c = Counter(payload['start'])\n    for delta in payload['deltas']: c.add(delta)\n    return c.value",
          [({"start": 3, "deltas": [2, -1]}, 4)], [({"start": 8, "deltas": []}, 8), ({"start": 0, "deltas": [-4, 4]}, 0)], ["4", "6"]),
    topic("python.objects", "Экземпляры и независимое состояние", ["python.classes"],
          "Два экземпляра одного класса имеют отдельные атрибуты экземпляра. Присваивание self.items=[] в __init__ создаёт отдельный список; items=[] в теле класса создаёт общий список. Изменение контейнера через одну ссылку видно всем ссылкам на тот же объект.",
          "class Bag:\n    def __init__(self): self.items = []\na, b = Bag(), Bag()\na.items.append('a')\nprint(len(a.items), len(b.items))", "1 0",
          "Где разместить список, который должен быть отдельным у каждого объекта?", ["В self.items внутри __init__", "В общем атрибуте класса items", "В одной глобальной переменной items"],
          ["Каждый вызов __init__ создаёт свой контейнер.", "Контейнер класса разделяется объектами.", "Глобальная ссылка не принадлежит конкретному объекту."],
          "В solve(payload) создайте два Bag с отдельными списками. Добавьте payload['left'] в первый, payload['right'] во второй. Верните [список первого,список второго]; не объединяйте их и не используйте общий атрибут класса.",
          "class Bag:\n    def __init__(self): self.items = []\ndef solve(payload):\n    a, b = Bag(), Bag()\n    a.items.extend(payload['left'])\n    b.items.extend(payload['right'])\n    return [a.items, b.items]",
          [({"left": [1], "right": [2, 3]}, [[1], [2, 3]])], [({"left": [], "right": [0]}, [[], [0]]), ({"left": [1, 1], "right": []}, [[1, 1], []])], ["1 1", "0 1"]),
    topic("python.inheritance", "Наследование и переопределение", ["python.objects"],
          "Подкласс наследует методы базового класса и может переопределить их. super() позволяет вызвать следующий метод по MRO, а не создаёт новый родительский объект. Наследование подходит для отношения 'является', когда контракт базового типа сохраняется.",
          "class Message:\n    def text(self): return 'hello'\nclass LoudMessage(Message):\n    def text(self): return super().text().upper()\nprint(LoudMessage().text())", "HELLO",
          "Что позволяет super() в переопределённом методе?", ["Вызвать следующий метод по порядку разрешения методов", "Скопировать все атрибуты в новый объект", "Выполнить все методы всех родителей без вызова"],
          ["super использует MRO и делегирует конкретный вызов.", "super не создаёт копию экземпляра.", "Другие методы не запускаются автоматически."],
          "В solve(payload) реализуйте BasePrice.total() возвращающий payload['base'] и DiscountPrice.total() с вызовом super(). Верните max(0, базовая цена минус payload['discount']). Все значения — неотрицательные целые.",
          "class BasePrice:\n    def __init__(self, base): self.base = base\n    def total(self): return self.base\nclass DiscountPrice(BasePrice):\n    def __init__(self, base, discount):\n        super().__init__(base)\n        self.discount = discount\n    def total(self): return max(0, super().total() - self.discount)\ndef solve(payload): return DiscountPrice(payload['base'], payload['discount']).total()",
          [({"base": 20, "discount": 3}, 17)], [({"base": 5, "discount": 8}, 0), ({"base": 0, "discount": 0}, 0)], ["hello", "None"]),
    topic("python.composition", "Композиция: делегирование объекту", ["python.inheritance"],
          "При композиции объект хранит другой объект и передаёт ему часть работы. Зависимость можно заменить без наследования. Это удобно для сервиса с разными способами отправки сообщений: сервис зависит от поведения отправителя, а не от конкретного транспорта.",
          "class Sender:\n    def send(self, text): return 'sent:' + text\nclass Service:\n    def __init__(self, sender): self.sender = sender\n    def notify(self): return self.sender.send('ok')\nprint(Service(Sender()).notify())", "sent:ok",
          "Как сервис использует вложенный отправитель при композиции?", ["Вызывает его метод через сохранённую зависимость", "Обязан наследовать класс отправителя", "Копирует исходный код отправителя в каждый метод"],
          ["Работа делегируется объекту с нужным поведением.", "Наследование не требуется для композиции.", "Копирование кода мешает заменять зависимость."],
          "В solve(payload) создайте PrefixFormatter(prefix) с методом format(text) и Report(formatter), делегирующий форматирование. Верните список отформатированных payload['messages']; prefix берётся из payload['prefix'], исходный порядок сохраняется.",
          "class PrefixFormatter:\n    def __init__(self, prefix): self.prefix = prefix\n    def format(self, text): return self.prefix + text\nclass Report:\n    def __init__(self, formatter): self.formatter = formatter\n    def render(self, messages): return [self.formatter.format(m) for m in messages]\ndef solve(payload): return Report(PrefixFormatter(payload['prefix'])).render(payload['messages'])",
          [({"prefix": "!", "messages": ["a", "b"]}, ["!a", "!b"])], [({"prefix": "", "messages": [""]}, [""]), ({"prefix": "x", "messages": []}, [])], ["ok", "sent:"]),
    topic("python.protocols", "Protocol: контракт по структуре", ["python.composition"],
          "typing.Protocol описывает требуемые методы и атрибуты для статической проверки. Явно наследовать Protocol реализации не обязательно. Проверки isinstance требуют @runtime_checkable и проверяют наличие членов, а не соответствие их аннотаций.",
          "from typing import Protocol, runtime_checkable\n@runtime_checkable\nclass Sized(Protocol):\n    def __len__(self) -> int: ...\nprint(isinstance([], Sized))", "True",
          "Что проверяет isinstance с runtime_checkable Protocol?", ["Наличие требуемых членов, а не их полные типовые сигнатуры", "Все типы аргументов при каждом вызове метода", "Только точное совпадение имени класса"],
          ["Runtime Protocol проверяет структуру; статическая проверка решает другую задачу.", "Аннотации не становятся полной runtime-валидацией.", "Структурный контракт не требует конкретного имени класса."],
          "В solve(payload) объявите Protocol Renderer с render(text)->str и реализацию UpperRenderer. Вызовите render для каждого payload['messages']; верните строки в верхнем регистре, включая пустые строки. Реализация не обязана наследовать Renderer.",
          "from typing import Protocol\nclass Renderer(Protocol):\n    def render(self, text: str) -> str: ...\nclass UpperRenderer:\n    def render(self, text): return text.upper()\ndef solve(payload):\n    renderer: Renderer = UpperRenderer()\n    return [renderer.render(x) for x in payload['messages']]",
          [({"messages": ["api", "Db"]}, ["API", "DB"])], [({"messages": ["", "ёж"]}, ["", "ЁЖ"]), ({"messages": []}, [])], ["False", "TypeError"]),
    topic("python.decorators", "Декоратор: обёртка вызова", ["python.protocols"],
          "Декоратор получает функцию и возвращает вызываемый объект. Обёртка может изменить поведение до или после исходного вызова; functools.wraps сохраняет метаданные. Декорирование выполняется при определении, а тело обёртки — при вызове.",
          "from functools import wraps\ndef twice(fn):\n    @wraps(fn)\n    def wrapped(x): return fn(x) * 2\n    return wrapped\n@twice\ndef amount(x): return x + 1\nprint(amount(3), amount.__name__)", "8 amount",
          "Зачем применять functools.wraps к обёртке?", ["Чтобы сохранить имя и другие метаданные исходной функции", "Чтобы автоматически вызвать функцию дважды", "Чтобы запретить аргументы функции"],
          ["wraps помогает инструментам и читателю видеть исходную функцию.", "Число вызовов определяет код обёртки.", "wraps не запрещает аргументы."],
          "В solve(payload) напишите декоратор clamp_zero: он заменяет отрицательный числовой результат на 0. Декорируйте функцию balance(income,expense), затем верните результат для payload['income'] и ['expense']. Сохраните имя функции через wraps.",
          "from functools import wraps\ndef clamp_zero(fn):\n    @wraps(fn)\n    def wrapped(*args, **kwargs): return max(0, fn(*args, **kwargs))\n    return wrapped\n@clamp_zero\ndef balance(income, expense): return income - expense\ndef solve(payload): return {'value': balance(payload['income'], payload['expense']), 'name': balance.__name__}",
          [({"income": 10, "expense": 4}, {"value": 6, "name": "balance"})], [({"income": 2, "expense": 7}, {"value": 0, "name": "balance"}), ({"income": 0, "expense": 0}, {"value": 0, "name": "balance"})], ["4 amount", "8 wrapped"]),
    topic("python.generators", "Генератор: значения по требованию", ["python.decorators"],
          "Функция с yield возвращает генератор. При next она работает до очередного yield и сохраняет состояние; при завершении поднимается StopIteration. Генератор одноразовый: повторный обход исчерпанного объекта не возвращает прежние значения.",
          "def ports():\n    yield 8000\n    yield 8001\ng = ports()\nprint(next(g))\nprint(list(g))", "8000\n[8001]",
          "Что делает yield в генераторе?", ["Отдаёт значение и приостанавливает выполнение с сохранением состояния", "Сразу строит список всех будущих значений", "Перезапускает функцию с первой строки"],
          ["Следующий next продолжит работу после yield.", "Генерация может быть ленивой и без готового списка.", "Состояние сохраняется, поэтому начало не повторяется."],
          "В solve(payload) реализуйте генератор positives(values), отдающий только числа строго больше нуля из payload['values'] в исходном порядке. Верните list(positives(...)); ноль пропускается, повторы сохраняются.",
          "def positives(values):\n    for value in values:\n        if value > 0: yield value\ndef solve(payload): return list(positives(payload['values']))",
          [({"values": [-1, 0, 2, 3]}, [2, 3])], [({"values": []}, []), ({"values": [1, 1, -2]}, [1, 1])], ["8000\n[8000, 8001]", "8001\n[]"]),
    topic("python.iterators", "Итератор и окончание обхода", ["python.generators"],
          "iter создаёт итератор, next запрашивает очередной элемент. При окончании next поднимает StopIteration либо возвращает переданный default. Цикл for использует этот протокол и завершает обход без выдачи исключения пользователю.",
          "it = iter(['GET'])\nprint(next(it))\nprint(next(it, 'done'))", "GET\ndone",
          "Что возвращает next(iterator, default) после исчерпания?", ["Переданный default", "Первый элемент заново", "Всегда пустой список"],
          ["Второй аргумент заменяет StopIteration при исчерпании.", "Итератор сам не перезапускается.", "Тип default выбирает вызывающий код."],
          "Напишите solve(payload), использующую iter и next для чтения не более payload['limit'] элементов из payload['values']. Верните прочитанные элементы. limit — неотрицательное целое; если данных меньше limit, завершите чтение без ошибки. Значение null внутри списка — обычный элемент.",
          "def solve(payload):\n    it = iter(payload['values'])\n    sentinel = object()\n    result = []\n    for _ in range(payload['limit']):\n        value = next(it, sentinel)\n        if value is sentinel: break\n        result.append(value)\n    return result",
          [({"values": [1, 2, 3], "limit": 2}, [1, 2])], [({"values": [None], "limit": 3}, [None]), ({"values": [1], "limit": 0}, [])], ["GET\nGET", "GET\n[]"]),
    topic("python.context_managers", "Контекстный менеджер и finally", ["python.iterators"],
          "with вызывает __enter__ и затем __exit__, включая выход при исключении после успешного входа. В generator context manager исключение бросается в точку yield; cleanup после yield без finally может быть пропущен. Для гарантированного освобождения ресурса используйте try/finally вокруг yield.",
          "from contextlib import contextmanager\n@contextmanager\ndef resource():\n    print('open')\n    try: yield 'db'\n    finally: print('close')\ntry:\n    with resource(): raise ValueError('bad')\nexcept ValueError:\n    print('handled')", "open\nclose\nhandled",
          "Как гарантировать cleanup в @contextmanager при ошибке внутри with?", ["Поместить cleanup в finally вокруг yield", "Написать cleanup только после yield без finally", "Написать cleanup перед yield"],
          ["finally выполняется и при нормальном выходе, и при исключении.", "Исключение в точке yield может пропустить следующий код.", "Освобождение до yield происходит до использования ресурса."],
          "В solve(payload) используйте @contextmanager для записи событий 'open' и 'close'. Внутри with добавьте 'use'; если payload['fail'] равно true, бросьте ValueError и обработайте с событием 'handled' снаружи. Верните список событий; close обязателен в обоих случаях.",
          "from contextlib import contextmanager\ndef solve(payload):\n    events = []\n    @contextmanager\n    def resource():\n        events.append('open')\n        try: yield\n        finally: events.append('close')\n    try:\n        with resource():\n            events.append('use')\n            if payload['fail']: raise ValueError('bad')\n    except ValueError: events.append('handled')\n    return events",
          [({"fail": False}, ["open", "use", "close"])], [({"fail": True}, ["open", "use", "close", "handled"])], ["open\nhandled", "open\nhandled\nclose"], minutes=24),
    topic("backend.authentication", "Аутентификация: проверка предъявленного секрета", ["backend.response_models"],
          "Аутентификация устанавливает, кто делает запрос. Bearer-токен проверяется сервером, а не считается верным из-за наличия заголовка. Секреты сравнивают безопасным способом и не записывают в логи. Неуспешная аутентификация отличается от отказа уже известному пользователю в доступе.",
          "import hmac\nprint(hmac.compare_digest('token-a', 'token-a'))\nprint(hmac.compare_digest('token-a', 'token-b'))", "True\nFalse",
          "Достаточно ли наличия Authorization для аутентификации?", ["Нет: сервер должен проверить предъявленные учётные данные", "Да: любой непустой заголовок подтверждает пользователя", "Да: имя заголовка является паролем"],
          ["Наличие заголовка не доказывает подлинность его значения.", "Злоумышленник может отправить произвольную строку.", "Имя протокольного поля публично и не является секретом."],
          "solve(payload) получает header и expected_token — ASCII-строки. Верните true, только если header начинается ровно с 'Bearer ' и оставшийся токен непустой и совпадает с expected_token. Используйте hmac.compare_digest; неверная схема, пустой токен и несовпадение дают false.",
          "import hmac\ndef solve(payload):\n    header = payload['header']\n    return header.startswith('Bearer ') and bool(header[7:]) and hmac.compare_digest(header[7:], payload['expected_token'])",
          [({"header": "Bearer abc", "expected_token": "abc"}, True)], [({"header": "Basic abc", "expected_token": "abc"}, False), ({"header": "Bearer ", "expected_token": ""}, False), ({"header": "Bearer ab", "expected_token": "abc"}, False)], ["True\nTrue", "False\nTrue"], phase=2),
    topic("backend.authorization", "Авторизация: проверка разрешённого действия", ["backend.authentication"],
          "Авторизация отвечает, что уже известному пользователю разрешено делать. Роль или право проверяется сервером при каждом защищённом действии. UI может скрыть кнопку, но это не заменяет проверку API. По умолчанию неизвестная роль не получает доступ.",
          "permissions = {'reader': {'read'}, 'editor': {'read', 'write'}}\nprint('write' in permissions['reader'])\nprint('write' in permissions['editor'])", "False\nTrue",
          "Где должна происходить проверка права изменить ресурс?", ["На сервере перед изменением ресурса", "Только в браузере перед показом кнопки", "Только при регистрации пользователя"],
          ["Иначе прямой запрос обойдёт интерфейс.", "Браузер контролируется пользователем.", "Права и действие могут измениться после регистрации."],
          "solve(payload) получает role и action. reader может read, editor — read/write, admin — read/write/delete. Верните bool разрешения. Неизвестная роль или действие запрещены, сравнение строк чувствительно к регистру.",
          "def solve(payload):\n    permissions = {'reader': {'read'}, 'editor': {'read', 'write'}, 'admin': {'read', 'write', 'delete'}}\n    return payload['action'] in permissions.get(payload['role'], set())",
          [({"role": "editor", "action": "write"}, True)], [({"role": "reader", "action": "delete"}, False), ({"role": "unknown", "action": "read"}, False), ({"role": "admin", "action": "drop"}, False)], ["True\nTrue", "True\nFalse"], phase=2),
    topic("backend.sessions", "Сессия: серверное состояние входа", ["backend.authorization"],
          "Cookie может содержать случайный идентификатор сессии, а сервер хранит владельца и срок действия. При выходе сервер отзывает сессию. Истёкшая сессия не становится действующей только потому, что браузер продолжает присылать cookie.",
          "session = {'expires_at': 100, 'revoked': False}\nnow = 100\nprint(not session['revoked'] and now < session['expires_at'])", "False",
          "Как трактовать сессию ровно в момент expires_at?", ["Как истёкшую, если действительность задана now < expires_at", "Как бессрочно действующую", "Как действующую до следующего входа"],
          ["Строгая граница не включает момент истечения.", "Срок действия ограничивает сессию.", "Следующий вход не определяет срок текущей сессии."],
          "solve(payload) получает sessions — словарь token -> {user,expires_at,revoked}, token и now (целые секунды). Верните user действующей сессии либо null. Условие: token существует, revoked=false и now<expires_at.",
          "def solve(payload):\n    s = payload['sessions'].get(payload['token'])\n    return s['user'] if s and not s['revoked'] and payload['now'] < s['expires_at'] else None",
          [({"sessions": {"a": {"user": "ira", "expires_at": 10, "revoked": False}}, "token": "a", "now": 9}, "ira")], [({"sessions": {"a": {"user": "ira", "expires_at": 10, "revoked": False}}, "token": "a", "now": 10}, None), ({"sessions": {}, "token": "a", "now": 0}, None), ({"sessions": {"a": {"user": "ira", "expires_at": 10, "revoked": True}}, "token": "a", "now": 0}, None)], ["True", "100"], phase=2),
    topic("backend.csrf", "CSRF: защита действий с cookie", ["backend.sessions"],
          "Браузер может автоматически приложить cookie к запросу, инициированному чужой страницей. Сервер проверяет CSRF-токен на изменяющих запросах; клиент должен передать значение, связанное с текущей сессией. SameSite и проверка Origin дополняют эту защиту. CSRF-токен не заменяет вход и авторизацию.",
          "safe_methods = {'GET', 'HEAD', 'OPTIONS'}\nprint('POST' not in safe_methods)\nprint('GET' not in safe_methods)", "True\nFalse",
          "Что должен проверять сервер для изменения через cookie-сессию?", ["CSRF-токен, связанный с этой сессией", "Только наличие кнопки на странице", "Только расширение URL"],
          ["Такой токен нельзя произвольно взять из чужой сессии.", "Чужая страница может инициировать запрос без кнопки приложения.", "Расширение пути не устанавливает происхождение запроса."],
          "solve(payload) получает method, supplied_token и session_token (строки). GET/HEAD/OPTIONS разрешите без токена. Для других методов требуется непустой session_token и безопасное сравнение с supplied_token. Верните bool; методы сравнивайте после upper(). Токены ASCII.",
          "import hmac\ndef solve(payload):\n    if payload['method'].upper() in {'GET', 'HEAD', 'OPTIONS'}: return True\n    return bool(payload['session_token']) and hmac.compare_digest(payload['supplied_token'], payload['session_token'])",
          [({"method": "POST", "supplied_token": "a", "session_token": "a"}, True)], [({"method": "post", "supplied_token": "a", "session_token": "b"}, False), ({"method": "GET", "supplied_token": "", "session_token": ""}, True), ({"method": "DELETE", "supplied_token": "", "session_token": ""}, False)], ["False\nFalse", "True\nTrue"], phase=2),
    topic("backend.password_hashing", "Пароли: соль и медленная проверка", ["backend.csrf"],
          "Пароль хранится через специализированную парольную функцию, а не в открытом виде и не как быстрый SHA256 без соли. Соль уникальна для записи и не является секретом. При проверке вычисляют результат с теми же параметрами и сравнивают безопасно. Для production выбирают текущие рекомендации и измеряют стоимость; параметры учебного примера не являются настройкой сервиса.",
          "import hashlib\na = hashlib.pbkdf2_hmac('sha256', b'pw', b'salt-a', 1000)\nb = hashlib.pbkdf2_hmac('sha256', b'pw', b'salt-b', 1000)\nprint(a != b)", "True",
          "Зачем нужна уникальная соль для пароля?", ["Чтобы одинаковые пароли не давали одинаковые сохранённые результаты", "Чтобы можно было восстановить пароль из хеша", "Чтобы хранить пароль в cookie"],
          ["Соль изменяет вычисляемый результат для каждой записи.", "Парольная функция не предназначена для обратного восстановления.", "Cookie не должна содержать исходный пароль."],
          "solve(payload) получает password,salt (UTF-8), expected_hex и iterations (1..10000, только учебные тесты). Вычислите PBKDF2-HMAC-SHA256 и верните {'matches':bool,'length':64}; matches сравнивает hex результата с expected_hex через compare_digest. Не возвращайте пароль.",
          "import hashlib, hmac\ndef solve(payload):\n    digest = hashlib.pbkdf2_hmac('sha256', payload['password'].encode(), payload['salt'].encode(), payload['iterations']).hex()\n    return {'matches': hmac.compare_digest(digest, payload['expected_hex']), 'length': len(digest)}",
          [({"password": "p", "salt": "s", "iterations": 1, "expected_hex": ""}, {"matches": False, "length": 64})], [({"password": "", "salt": "s", "iterations": 2, "expected_hex": "0" * 64}, {"matches": False, "length": 64})], ["False", "salt-a"], phase=2),
    topic("backend.async_python", "async def и await", ["backend.password_hashing"],
          "Вызов async def создаёт coroutine; выполнение запускается await или планированием задачи. await позволяет event loop переключаться во время ожидания. CPU-работа без await и блокирующий sleep по-прежнему блокируют поток; async не превращает вычисления в параллельные.",
          "import asyncio\nasync def value(): return 7\nasync def main(): print(await value())\nasyncio.run(main())", "7",
          "Что создаёт вызов async def до await?", ["Объект coroutine", "Отдельный процесс ОС", "Готовый результат в любом случае"],
          ["Coroutine нужно дождаться или запланировать.", "async def не создаёт процесс.", "Тело ещё не обязано выполниться."],
          "solve(payload) получает values — список целых. Определите async-функцию double, верните удвоенные значения через asyncio.run и await, сохранив порядок. Пустой список даёт пустой результат. Не используйте сеть или задержки.",
          "import asyncio\nasync def double(x): return x * 2\nasync def run(values): return [await double(x) for x in values]\ndef solve(payload): return asyncio.run(run(payload['values']))",
          [({"values": [2, -1]}, [4, -2])], [({"values": []}, []), ({"values": [0, 3, 3]}, [0, 6, 6])], ["coroutine", "None"], phase=2),
    topic("backend.async_io", "Несколько ожидающих операций", ["backend.async_python"],
          "asyncio.gather ожидает несколько awaitable и возвращает результаты в порядке аргументов. Это полезно для независимых I/O-операций; общий доступ к состоянию всё равно требует дисциплины. При использовании gather не следует обещать параллельный CPU-прогон.",
          "import asyncio\nasync def number(n):\n    await asyncio.sleep(0)\n    return n\nasync def main(): print(await asyncio.gather(number(2), number(1)))\nasyncio.run(main())", "[2, 1]",
          "В каком порядке gather возвращает успешные результаты?", ["В порядке переданных awaitable", "Всегда по числовой величине", "Обязательно в порядке завершения"],
          ["Порядок результата соответствует аргументам gather.", "gather не сортирует значения.", "Порядок завершения может отличаться от результата."],
          "solve(payload) получает names — список строк. Через async-функцию fetch и asyncio.gather верните список {'name':name,'size':len(name)} в исходном порядке. fetch может делать await asyncio.sleep(0), но не обращается к сети.",
          "import asyncio\nasync def fetch(name):\n    await asyncio.sleep(0)\n    return {'name': name, 'size': len(name)}\nasync def run(names): return await asyncio.gather(*(fetch(n) for n in names))\ndef solve(payload): return asyncio.run(run(payload['names']))",
          [({"names": ["db", "api"]}, [{"name": "db", "size": 2}, {"name": "api", "size": 3}])], [({"names": []}, []), ({"names": ["", "я"]}, [{"name": "", "size": 0}, {"name": "я", "size": 1}])], ["[1, 2]", "[2]"], phase=2),
    topic("backend.background_tasks", "Фоновая задача и долговечная очередь", ["backend.async_io"],
          "FastAPI BackgroundTasks выполняет добавленные задачи после отправки ответа в процессе приложения. Это удобно для небольших действий, но не даёт долговечную доставку: авария процесса может потерять работу. Критичные задания требуют сохранённой очереди, идемпотентности и наблюдения за состоянием.",
          "from fastapi import BackgroundTasks\nimport asyncio\nevents = []\ntasks = BackgroundTasks()\ntasks.add_task(events.append, 'sent')\nprint(events)\nasyncio.run(tasks())\nprint(events)", "[]\n['sent']",
          "Гарантирует ли BackgroundTasks доставку после аварии процесса?", ["Нет: для долговечной доставки нужна сохранённая очередь", "Да: задача автоматически хранится в PostgreSQL", "Да: задача всегда запускается отдельным сервером"],
          ["Встроенные задачи живут в процессе приложения.", "BackgroundTasks не создаёт таблицу очереди.", "Отдельный worker не возникает автоматически."],
          "solve(payload) получает jobs — записи с id и message. Моделируйте идемпотентную обработку: верните messages первого появления каждого id в исходном порядке. Повторный id не выполняется второй раз даже при другом message; пустая очередь даёт [].",
          "def solve(payload):\n    seen = set()\n    result = []\n    for job in payload['jobs']:\n        if job['id'] not in seen:\n            seen.add(job['id'])\n            result.append(job['message'])\n    return result",
          [({"jobs": [{"id": "a", "message": "one"}, {"id": "a", "message": "two"}]}, ["one"])], [({"jobs": []}, []), ({"jobs": [{"id": "a", "message": ""}, {"id": "b", "message": "x"}]}, ["", "x"])], ["['sent']\n['sent']", "[]\n[]"], phase=2),
    topic("backend.logging", "Логи: полезное событие без секретов", ["backend.background_tasks"],
          "Лог содержит событие, уровень и безопасный контекст. Пароли, токены и cookie в него не помещают. Форматирование через аргументы logging отделяет шаблон от данных; записи позволяют расследовать сбой, но не заменяют метрики.",
          "import logging\nlogger = logging.getLogger('example')\nlogger.setLevel(logging.INFO)\nprint(logger.isEnabledFor(logging.INFO))\nprint(logger.isEnabledFor(logging.DEBUG))", "True\nFalse",
          "Какие данные следует исключить из лога запроса?", ["Пароли и значения токенов", "Тип события", "Безопасный request_id"],
          ["Секрет в логе может стать доступен оператору или внешней системе.", "Событие помогает понять, что произошло.", "Случайный request_id связывает безопасные записи одного запроса."],
          "solve(payload) получает event — словарь. Верните новый словарь только с ключами event,request_id,status, если они существуют. Все остальные поля, включая password/token/cookie, исключите; значения разрешённых полей сохраняются.",
          "def solve(payload): return {k: v for k, v in payload['event'].items() if k in {'event', 'request_id', 'status'}}",
          [({"event": {"event": "login", "token": "secret", "status": 401}}, {"event": "login", "status": 401})], [({"event": {"password": "p"}}, {}), ({"event": {"request_id": "r", "event": "", "status": 0, "cookie": "s"}}, {"request_id": "r", "event": "", "status": 0})], ["True\nTrue", "False\nFalse"], phase=2),
    topic("backend.configuration", "Конфигурация: граница и проверка", ["backend.logging"],
          "Конфигурацию читают и валидируют на границе запуска приложения. Строка 'false' не должна превращаться в true из-за bool('false'). Обязательные значения и диапазоны проверяются явно; неверная конфигурация должна быть понятной ошибкой, а не скрытым fallback.",
          "raw = 'false'\nprint(bool(raw))\nprint(raw.lower() == 'true')", "True\nFalse",
          "Почему bool('false') опасен для настройки флага?", ["Непустая строка истинна независимо от её текста", "Python автоматически переводит её в False", "bool проверяет имя переменной"],
          ["Текстовое значение нужно разобрать по явному контракту.", "bool не разбирает слово false.", "Истинность зависит от значения, а не имени."],
          "solve(payload) получает enabled и port как строки. enabled принимается только 'true' или 'false' без учёта регистра; port — целое 1..65535. Верните {'enabled':bool,'port':int}, а при неверном формате/диапазоне — {'error':'invalid_config'}. Пробелы вокруг значений удалите.",
          "def solve(payload):\n    raw = payload['enabled'].strip().lower()\n    try: port = int(payload['port'].strip())\n    except ValueError: return {'error': 'invalid_config'}\n    if raw not in {'true', 'false'} or not 1 <= port <= 65535: return {'error': 'invalid_config'}\n    return {'enabled': raw == 'true', 'port': port}",
          [({"enabled": "false", "port": "8000"}, {"enabled": False, "port": 8000})], [({"enabled": "yes", "port": "80"}, {"error": "invalid_config"}), ({"enabled": " TRUE ", "port": "65536"}, {"error": "invalid_config"}), ({"enabled": "TRUE", "port": " 1 "}, {"enabled": True, "port": 1})], ["False\nFalse", "False\nTrue"], phase=2),
    topic("backend.environment_variables", "Переменные окружения: строки и отсутствие", ["backend.configuration"],
          "Окружение передаёт строки процессу. Отсутствие ключа и пустая строка различны. Переменные удобно использовать для конфигурации, но секреты нельзя включать в публичную сборку клиента или печатать при диагностике. Изменение родительского окружения не меняет уже запущенный процесс.",
          "env = {'PORT': ''}\nprint(env.get('MISSING') is None)\nprint(env.get('PORT') == '')", "True\nTrue",
          "Чем отличается отсутствующий ключ от пустой переменной?", ["get без default даёт None для отсутствующего и '' для пустого", "Оба всегда дают строку 'None'", "Пустая строка автоматически удаляет ключ"],
          ["Эти состояния можно проверить отдельно.", "None является отдельным значением Python.", "Пустое значение может оставаться в окружении."],
          "solve(payload) получает env — словарь строк, key и default. Если key отсутствует, верните default; если присутствует, верните его значение, даже пустую строку. Не читайте настоящее окружение worker.",
          "def solve(payload): return payload['env'].get(payload['key'], payload['default'])",
          [({"env": {"PORT": "8000"}, "key": "PORT", "default": "80"}, "8000")], [({"env": {"PORT": ""}, "key": "PORT", "default": "80"}, ""), ({"env": {}, "key": "PORT", "default": "80"}, "80")], ["True\nFalse", "False\nTrue"], phase=2),
    topic("backend.error_handling", "Ошибки: публичный ответ и внутренняя причина", ["backend.environment_variables", "python.exceptions"],
          "Внешнему клиенту возвращают стабильный код и безопасное сообщение. Детали исключения, SQL, секреты и stack trace не становятся публичным ответом. Ошибки валидации, отсутствие ресурса и внутренний сбой имеют разные семантики; обработка ошибки не должна выдавать ложный успех.",
          "status = {'invalid': 422, 'missing': 404, 'internal': 500}\nprint(status['missing'])\nprint(status['internal'])", "404\n500",
          "Что вернуть клиенту при внутреннем исключении?", ["Безопасный ответ 500 без внутреннего traceback", "Ответ 200 с текстом traceback", "Пароль БД для диагностики"],
          ["Детали остаются в защищённом внутреннем контуре.", "200 обозначает успех и искажает результат.", "Секрет не является частью публичной диагностики."],
          "solve(payload) получает kind: invalid,missing или любое другое значение. Верните {'status':422,'detail':'invalid_input'}, {'status':404,'detail':'not_found'} либо {'status':500,'detail':'internal_error'} соответственно. Поле exception, если есть, не возвращайте.",
          "def solve(payload):\n    codes = {'invalid': (422, 'invalid_input'), 'missing': (404, 'not_found')}\n    status, detail = codes.get(payload['kind'], (500, 'internal_error'))\n    return {'status': status, 'detail': detail}",
          [({"kind": "missing"}, {"status": 404, "detail": "not_found"})], [({"kind": "invalid"}, {"status": 422, "detail": "invalid_input"}), ({"kind": "db", "exception": "secret"}, {"status": 500, "detail": "internal_error"})], ["500\n404", "404\n200"], phase=2),
    topic("backend.middleware", "Middleware: обёртка запроса", ["backend.error_handling"],
          "Middleware выполняет общую работу вокруг обработчика: до передачи запроса и после ответа. Порядок обёрток влияет на поведение. Middleware не заменяет доменные проверки; в нём удобно добавлять request_id и безопасные заголовки.",
          "events = []\ndef handler():\n    events.append('handler')\n    return 'ok'\ndef middleware():\n    events.append('before')\n    value = handler()\n    events.append('after')\n    return value\nmiddleware()\nprint(events)", "['before', 'handler', 'after']",
          "Когда выполняется код middleware после вызова обработчика?", ["После получения его результата, если управление вернулось нормально", "До кода before в той же функции", "Никогда: middleware только перед запросом"],
          ["Обёртка может обрабатывать и запрос, и ответ.", "Порядок обычных строк Python сохраняется.", "Обработка ответа — типичная задача middleware."],
          "solve(payload) получает response_headers — словарь и request_id. Верните новый словарь заголовков, добавив/заменив X-Request-ID значением request_id. Исходный словарь не меняйте; другие ключи сохраните.",
          "def solve(payload):\n    result = dict(payload['response_headers'])\n    result['X-Request-ID'] = payload['request_id']\n    return result",
          [({"response_headers": {"Content-Type": "application/json"}, "request_id": "r1"}, {"Content-Type": "application/json", "X-Request-ID": "r1"})], [({"response_headers": {"X-Request-ID": "old"}, "request_id": "new"}, {"X-Request-ID": "new"}), ({"response_headers": {}, "request_id": "r"}, {"X-Request-ID": "r"})], ["['handler', 'before', 'after']", "['before', 'after', 'handler']"], phase=2),
    topic("backend.openapi", "OpenAPI: машиночитаемый контракт", ["backend.middleware"],
          "OpenAPI описывает пути, операции, параметры, request bodies и ответы API. Схема помогает документации и генерации клиентов, но сама не исполняет бизнес-правила. В FastAPI типы и response models участвуют в её построении; секретные серверные поля не входят в публичную модель.",
          "schema = {'paths': {'/users': {'get': {}, 'post': {}}}}\nprint(sorted(schema['paths']['/users']))", "['get', 'post']",
          "Что описывает OpenAPI?", ["Контракт операций и схем данных API", "Только CSS страницы документации", "Фактический результат каждого запроса в БД"],
          ["Клиент может узнать ожидаемые параметры и ответы.", "OpenAPI является форматом данных, а не темой страницы.", "Схема не является журналом выполнения."],
          "solve(payload) получает paths — OpenAPI-подобный словарь path->{операции}. Верните отсортированные строки 'METHOD path' для get/post/put/patch/delete/head/options/trace; ключи parameters/summary игнорируйте. METHOD в верхнем регистре.",
          "def solve(payload):\n    methods = {'get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace'}\n    return sorted(method.upper() + ' ' + path for path, operations in payload['paths'].items() for method in operations if method in methods)",
          [({"paths": {"/users": {"get": {}, "post": {}, "parameters": []}}}, ["GET /users", "POST /users"])], [({"paths": {}}, []), ({"paths": {"/x": {"summary": "x", "delete": {}}}}, ["DELETE /x"])], ["['post', 'get']", "['/users']"], phase=2),
    topic("backend.websockets", "WebSocket: сообщения в открытом соединении", ["backend.openapi"],
          "WebSocket после handshake поддерживает двусторонний обмен сообщениями через одно соединение. Сервер должен проверять доступ и содержимое сообщений, ограничивать размер и обрабатывать отключение. Открытое соединение не означает, что пользователь получил право на любые действия.",
          "messages = ['hello', 'ping', 'bye']\nprint([message.upper() for message in messages])", "['HELLO', 'PING', 'BYE']",
          "Что отличает WebSocket от отдельных HTTP-запросов?", ["Двусторонний обмен сообщениями через открытое соединение", "Отсутствие необходимости проверять пользователя", "Обязательная запись всех сообщений в файл"],
          ["После handshake стороны могут отправлять сообщения.", "Аутентификация и права по-прежнему нужны.", "Сохранение сообщений определяется приложением."],
          "solve(payload) получает messages — список строк и max_length — неотрицательное целое. Обработайте каждую строку: если длина превышает max_length, верните 'error:too_large', если строка 'ping' — 'pong', иначе 'echo:'+строка. Сохраните порядок, пустая строка допустима.",
          "def solve(payload): return ['error:too_large' if len(m) > payload['max_length'] else 'pong' if m == 'ping' else 'echo:' + m for m in payload['messages']]",
          [({"messages": ["ping", "hi"], "max_length": 4}, ["pong", "echo:hi"])], [({"messages": ["ping", ""], "max_length": 0}, ["error:too_large", "echo:"]), ({"messages": [], "max_length": 8}, [])], ["['hello', 'ping', 'bye']", "['HELLO', 'PONG', 'BYE']"], phase=2),
    topic("backend.sql_basics", "SQL: таблица, строка и ключ", ["backend.websockets"],
          "Реляционная таблица хранит строки с полями. PRIMARY KEY идентифицирует строку; SELECT читает выбранные столбцы. SQL-запрос описывает нужный результат, а не порядок обхода. Значения передают параметрами драйвера, не конкатенацией пользовательской строки.",
          "import sqlite3\nwith sqlite3.connect(':memory:') as db:\n    db.execute('CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT)')\n    db.execute('INSERT INTO users VALUES (?, ?)', (1, 'Ira'))\n    print(db.execute('SELECT name FROM users WHERE id = ?', (1,)).fetchone()[0])", "Ira",
          "Зачем передавать значения запроса параметрами?", ["Чтобы данные не интерпретировались как часть SQL-кода", "Чтобы любые запросы стали быстрее", "Чтобы отменить необходимость проверять права"],
          ["Драйвер отделяет значения от текста запроса.", "Параметризация не гарантирует ускорение каждого запроса.", "Права на действие проверяются отдельно."],
          "solve(payload) получает users — записи {id,name}, wanted_id. Создайте in-memory SQLite-таблицу с этими данными, параметризованным SELECT найдите имя по id. Верните имя или null. id уникальны; имена могут содержать апостроф.",
          "import sqlite3\ndef solve(payload):\n    with sqlite3.connect(':memory:') as db:\n        db.execute('CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT)')\n        db.executemany('INSERT INTO users VALUES (?, ?)', [(r['id'], r['name']) for r in payload['users']])\n        row = db.execute('SELECT name FROM users WHERE id = ?', (payload['wanted_id'],)).fetchone()\n        return row[0] if row else None",
          [({"users": [{"id": 1, "name": "Ira"}], "wanted_id": 1}, "Ira")], [({"users": [], "wanted_id": 1}, None), ({"users": [{"id": 2, "name": "O'Reilly"}], "wanted_id": 2}, "O'Reilly")], ["1", "None"], phase=3),
    topic("backend.postgresql", "PostgreSQL: идентификаторы и параметры", ["backend.sql_basics"],
          "PostgreSQL — серверная СУБД с транзакциями и конкурентными подключениями. Параметры драйвера применяются к значениям, а не к именам таблиц. Идентификатор заключают в двойные кавычки с удвоением внутренней кавычки либо используют композицию SQL драйвера; имена из пользователя лучше ограничивать allowlist.",
          "identifier = 'user\"data'\nquoted = '\"' + identifier.replace('\"', '\"\"') + '\"'\nprint(quoted)", '"user""data"',
          "Можно ли обычным параметром значения заменить имя таблицы?", ["Нет: идентификатор требует отдельной безопасной композиции SQL", "Да: все параметры заменяют любой текст запроса", "Да: для этого нужно убрать кавычки"],
          ["Имена SQL-объектов и значения имеют разные правила.", "Драйвер не делает произвольную текстовую подстановку.", "Удаление кавычек не создаёт безопасный идентификатор."],
          "solve(payload) получает identifier — непустую строку без NUL. Верните PostgreSQL quoted identifier: двойная кавычка с обеих сторон, внутренние двойные кавычки удвоены. Пробелы и апострофы сохраните. Это упражнение по композиции, не запуск PostgreSQL.",
          "def solve(payload): return '\"' + payload['identifier'].replace('\"', '\"\"') + '\"'",
          [({"identifier": "users"}, '"users"')], [({"identifier": 'a"b'}, '"a""b"'), ({"identifier": "O'Reilly table"}, '"O\'Reilly table"')], ['"user"data"', "userdata"], phase=3),
    topic("backend.sql_select", "SELECT: фильтр, порядок и лимит", ["backend.postgresql"],
          "WHERE фильтрует строки, ORDER BY задаёт порядок результата, LIMIT ограничивает число строк. Без ORDER BY порядок не обещан. Для стабильного выбора при одинаковом основном значении добавляют уникальный tie-breaker, например id.",
          "import sqlite3\nwith sqlite3.connect(':memory:') as db:\n    db.execute('CREATE TABLE scores(id INTEGER, score INTEGER)')\n    db.executemany('INSERT INTO scores VALUES (?,?)', [(2,9),(1,9),(3,4)])\n    print(db.execute('SELECT id FROM scores ORDER BY score DESC, id ASC LIMIT 2').fetchall())", "[(1,), (2,)]",
          "Как получить стабильный порядок строк с одинаковым score?", ["Добавить уникальный id как дополнительный ORDER BY", "Полагаться на порядок вставки", "Убрать ORDER BY и оставить LIMIT"],
          ["Tie-breaker определяет порядок равных значений.", "Физический порядок без контракта может измениться.", "LIMIT не задаёт сортировку."],
          "solve(payload) получает rows:{id,score}, min_score и limit>=0. Через SQLite SELECT верните id строк с score>=min_score, сортируя score DESC затем id ASC, не более limit строк. id уникальны.",
          "import sqlite3\ndef solve(payload):\n    with sqlite3.connect(':memory:') as db:\n        db.execute('CREATE TABLE scores(id INTEGER, score INTEGER)')\n        db.executemany('INSERT INTO scores VALUES (?,?)', [(r['id'],r['score']) for r in payload['rows']])\n        return [r[0] for r in db.execute('SELECT id FROM scores WHERE score >= ? ORDER BY score DESC, id ASC LIMIT ?', (payload['min_score'],payload['limit']))]",
          [({"rows": [{"id": 2, "score": 9}, {"id": 1, "score": 9}], "min_score": 5, "limit": 2}, [1, 2])], [({"rows": [], "min_score": 0, "limit": 3}, []), ({"rows": [{"id": 1, "score": 5}], "min_score": 5, "limit": 0}, [])], ["[(2,), (1,)]", "[(3,), (1,)]"], phase=3),
    topic("backend.sql_joins", "JOIN: объединение связанных строк", ["backend.sql_select"],
          "INNER JOIN оставляет совпавшие пары. LEFT JOIN сохраняет все строки слева, а при отсутствии пары справа даёт NULL. Несколько подходящих строк справа размножают результат; JOIN не обещает один результат на пользователя.",
          "import sqlite3\nwith sqlite3.connect(':memory:') as db:\n    db.executescript('CREATE TABLE users(id INT); CREATE TABLE orders(user_id INT); INSERT INTO users VALUES (1),(2); INSERT INTO orders VALUES (1);')\n    print(db.execute('SELECT u.id, o.user_id FROM users u LEFT JOIN orders o ON o.user_id=u.id ORDER BY u.id').fetchall())", "[(1, 1), (2, None)]",
          "Что даёт LEFT JOIN для строки слева без совпадения справа?", ["Сохраняет строку слева и NULL в полях справа", "Всегда удаляет строку слева", "Создаёт физическую строку в правой таблице"],
          ["Это отличие от INNER JOIN.", "Удаление несопоставленных строк характерно для INNER JOIN.", "SELECT не создаёт недостающие записи."],
          "solve(payload) получает users:[{id}],orders:[{id,user_id}]. Через LEFT JOIN верните пары [user_id,order_id] отсортированные по user_id затем order_id. Для пользователя без заказов верните [user_id,null]. id уникальны внутри таблицы.",
          "import sqlite3\ndef solve(payload):\n    with sqlite3.connect(':memory:') as db:\n        db.executescript('CREATE TABLE users(id INTEGER); CREATE TABLE orders(id INTEGER, user_id INTEGER);')\n        db.executemany('INSERT INTO users VALUES (?)', [(r['id'],) for r in payload['users']])\n        db.executemany('INSERT INTO orders VALUES (?,?)', [(r['id'],r['user_id']) for r in payload['orders']])\n        return [list(r) for r in db.execute('SELECT u.id,o.id FROM users u LEFT JOIN orders o ON o.user_id=u.id ORDER BY u.id,o.id')]",
          [({"users": [{"id": 1}, {"id": 2}], "orders": [{"id": 8, "user_id": 1}]}, [[1, 8], [2, None]])], [({"users": [], "orders": []}, []), ({"users": [{"id": 1}], "orders": [{"id": 9, "user_id": 1}, {"id": 8, "user_id": 1}]}, [[1, 8], [1, 9]])], ["[(1, 1)]", "[(1, 1), (2, 2)]"], phase=3),
    topic("backend.sql_indexes", "Индекс: поиск и цена записи", ["backend.sql_joins"],
          "Индекс ускоряет подходящие чтения за счёт структуры поиска, но занимает место и обновляется при записи. Составной B-tree индекс особенно полезен по ведущим столбцам. Выбор подтверждают планом запроса и измерениями; индекс не гарантирует ускорение каждого SELECT.",
          "import sqlite3\nwith sqlite3.connect(':memory:') as db:\n    db.execute('CREATE TABLE users(email TEXT)')\n    db.execute('CREATE INDEX ix_email ON users(email)')\n    plan = db.execute('EXPLAIN QUERY PLAN SELECT * FROM users WHERE email=?', ('a',)).fetchall()\n    print(any('INDEX' in row[3] for row in plan))", "True",
          "Какова цена дополнительного индекса?", ["Место и работа при изменении индексированных данных", "Полное запрещение INSERT", "Автоматическое удаление дубликатов всех столбцов"],
          ["Индекс поддерживается вместе с таблицей.", "Обычный индекс не запрещает вставки.", "Уникальность требует отдельного UNIQUE-контракта."],
          "solve(payload) получает index_columns и filter_columns — списки имён. Верните число ведущих столбцов индекса, присутствующих в filter_columns подряд до первого отсутствующего. Это упражнение по left-prefix правилу, не прогноз скорости запроса.",
          "def solve(payload):\n    available = set(payload['filter_columns'])\n    count = 0\n    for column in payload['index_columns']:\n        if column not in available: break\n        count += 1\n    return count",
          [({"index_columns": ["tenant", "email"], "filter_columns": ["tenant"]}, 1)], [({"index_columns": ["tenant", "email"], "filter_columns": ["email"]}, 0), ({"index_columns": [], "filter_columns": []}, 0), ({"index_columns": ["a", "b"], "filter_columns": ["b", "a"]}, 2)], ["False", "None"], phase=3),
    topic("backend.transactions", "Транзакция: всё или ничего", ["backend.sql_indexes"],
          "Транзакция объединяет изменения: COMMIT фиксирует их, ROLLBACK отменяет. Перевод между счетами должен уменьшить один баланс и увеличить другой атомарно. Проверки бизнес-правил выполняются в той же транзакции; конкурентный доступ требует подходящих блокировок или ограничений.",
          "import sqlite3\nwith sqlite3.connect(':memory:') as db:\n    db.execute('CREATE TABLE account(balance INTEGER)')\n    db.execute('INSERT INTO account VALUES (10)')\n    db.commit()\n    db.execute('UPDATE account SET balance=0')\n    db.rollback()\n    print(db.execute('SELECT balance FROM account').fetchone()[0])", "10",
          "Что делает ROLLBACK с незафиксированными изменениями?", ["Отменяет их в текущей транзакции", "Фиксирует их навсегда", "Удаляет структуру всех таблиц"],
          ["До COMMIT изменения можно отменить.", "Фиксация — задача COMMIT.", "Откат DML не означает удаление всей схемы."],
          "solve(payload) получает balances — [источник,получатель] и amount>=0. Если источнику хватает средств, верните {'ok':true,'balances':[source-amount,destination+amount]}; иначе {'ok':false,'balances':исходные}. Частичное изменение запрещено.",
          "def solve(payload):\n    a,b = payload['balances']\n    amount = payload['amount']\n    if a < amount: return {'ok': False, 'balances': [a,b]}\n    return {'ok': True, 'balances': [a-amount,b+amount]}",
          [({"balances": [10, 2], "amount": 3}, {"ok": True, "balances": [7, 5]})], [({"balances": [1, 9], "amount": 2}, {"ok": False, "balances": [1, 9]}), ({"balances": [0, 0], "amount": 0}, {"ok": True, "balances": [0, 0]})], ["0", "None"], phase=3),
    topic("backend.isolation", "Изоляция: наблюдение и конкурентные записи", ["backend.transactions"],
          "Уровень изоляции определяет, какие изменения другой транзакции можно наблюдать. В PostgreSQL READ COMMITTED каждый оператор получает снимок на начало оператора; REPEATABLE READ удерживает снимок транзакции. Изоляция не отменяет необходимость обрабатывать конфликты и повторять отменённые транзакции.",
          "snapshot = {'balance': 10}\nlive = dict(snapshot)\nlive['balance'] = 20\nprint(snapshot['balance'], live['balance'])", "10 20",
          "Как ведёт себя снимок REPEATABLE READ при повторном чтении?", ["Сохраняет видимость по снимку транзакции", "Обязательно видит каждый новый COMMIT сразу", "Позволяет читать незавершённые записи любой транзакции"],
          ["Снимок не заменяется новым для каждого чтения.", "Это отличается от READ COMMITTED.", "PostgreSQL не допускает dirty reads на этих уровнях."],
          "solve(payload) получает initial, committed — целые значения и level. Верните два чтения: для 'read_committed' [initial,committed], для 'repeatable_read' [initial,initial]. Неизвестный level верните {'error':'unknown_level'}. Это модель видимости, не нагрузочный тест СУБД.",
          "def solve(payload):\n    if payload['level'] == 'read_committed': return [payload['initial'],payload['committed']]\n    if payload['level'] == 'repeatable_read': return [payload['initial'],payload['initial']]\n    return {'error':'unknown_level'}",
          [({"initial": 10, "committed": 20, "level": "read_committed"}, [10, 20])], [({"initial": 10, "committed": 20, "level": "repeatable_read"}, [10, 10]), ({"initial": 0, "committed": 2, "level": "other"}, {"error": "unknown_level"})], ["20 20", "10 10"], phase=3),
    topic("backend.migrations", "Миграция: изменение схемы с данными", ["backend.isolation"],
          "Миграция меняет схему явной ревизией. При добавлении обязательного поля существующим строкам нужен корректный default или этап backfill. Upgrade и downgrade проверяют с сохранёнными sentinel-данными; откат структуры может быть разрушительным и требует понятной политики.",
          "import sqlite3\nwith sqlite3.connect(':memory:') as db:\n    db.executescript('CREATE TABLE users(id INTEGER); INSERT INTO users VALUES (1);')\n    db.execute('ALTER TABLE users ADD COLUMN active INTEGER NOT NULL DEFAULT 1')\n    print(db.execute('SELECT id,active FROM users').fetchall())", "[(1, 1)]",
          "Что учитывать при добавлении NOT NULL столбца в непустую таблицу?", ["Значение для существующих строк и совместимость приложения", "Только название файла миграции", "Удаление всех старых строк без необходимости"],
          ["Существующие строки должны удовлетворять новому ограничению.", "Название не решает вопрос данных.", "Удаление данных не является обязательной частью миграции."],
          "solve(payload) получает rows — словари существующих пользователей и default_active — bool. Верните копии rows: существующий ключ active сохраните, отсутствующий заполните default_active. Не потеряйте другие поля и порядок.",
          "def solve(payload): return [dict({'active':payload['default_active']}, **row) for row in payload['rows']]",
          [({"rows": [{"id": 1}], "default_active": True}, [{"id": 1, "active": True}])], [({"rows": [{"id": 1, "active": False, "name": "I"}], "default_active": True}, [{"id": 1, "active": False, "name": "I"}]), ({"rows": [], "default_active": False}, [])], ["[(1, None)]", "[]"], phase=3),
    topic("backend.sqlalchemy_core", "SQLAlchemy Core: построение выражений", ["backend.migrations"],
          "SQLAlchemy Core строит SQL из Table, столбцов и выражений. Значения превращаются в bind parameters; Connection исполняет выражение внутри явной транзакции. Core не требует ORM-классов; результат — строки выбранных столбцов.",
          "from sqlalchemy import column, select\nstmt = select(column('id')).where(column('id') == 3)\nprint(stmt.compile().params)", "{'id_1': 3}",
          "Во что SQLAlchemy превращает значение сравнения column('id') == 3?", ["В bind parameter выражения", "В имя новой таблицы", "В уже выполненный запрос к БД"],
          ["Построение выражения ещё не исполняет запрос.", "Значение не является идентификатором таблицы.", "Для исполнения нужна Connection или Session."],
          "solve(payload) получает filters — список {column,value}. Сформируйте безопасный план с clauses ['column = :p0',...] и params {'p0':value,...}. Имена column допускаются только id,name,active; неизвестное имя даёт {'error':'invalid_column'}. Значения никогда не вставляйте в текст clauses.",
          "def solve(payload):\n    if any(f['column'] not in {'id','name','active'} for f in payload['filters']): return {'error':'invalid_column'}\n    return {'clauses':[f['column']+' = :p'+str(i) for i,f in enumerate(payload['filters'])], 'params':{'p'+str(i):f['value'] for i,f in enumerate(payload['filters'])}}",
          [({"filters": [{"column": "id", "value": 3}]}, {"clauses": ["id = :p0"], "params": {"p0": 3}})], [({"filters": [{"column": "name", "value": "' OR 1=1"}]}, {"clauses": ["name = :p0"], "params": {"p0": "' OR 1=1"}}), ({"filters": [{"column": "x", "value": 1}]}, {"error": "invalid_column"}), ({"filters": []}, {"clauses": [], "params": {}})], ["{'id': 3}", "{}"], phase=3),
    topic("backend.sqlalchemy_orm", "ORM: объект и единица работы", ["backend.sqlalchemy_core"],
          "ORM связывает классы с таблицами, а Session управляет единицей работы. add делает объект pending, flush отправляет изменения в текущую транзакцию, commit фиксирует её. Flush не равен commit; rollback отменяет незафиксированные изменения.",
          "from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column\nclass Base(DeclarativeBase): pass\nclass User(Base):\n    __tablename__ = 'users'\n    id: Mapped[int] = mapped_column(primary_key=True)\nprint(User.__table__.name)", "users",
          "Чем flush отличается от commit?", ["Flush отправляет изменения, commit фиксирует транзакцию", "Оба всегда фиксируют транзакцию", "Flush удаляет Session навсегда"],
          ["После flush изменения ещё могут быть отменены rollback.", "Они имеют разные гарантии долговечности.", "flush не закрывает Session автоматически."],
          "solve(payload) получает stored — список целых id и actions:{kind,id}. Моделируйте единицу работы: add кладёт id в pending; flush не меняет stored; rollback очищает pending; commit дописывает pending в stored и очищает pending. Верните {'stored':список,'pending':список}. Допустимы только эти действия, для flush/rollback/commit id не нужен.",
          "def solve(payload):\n    stored=list(payload['stored']); pending=[]\n    for action in payload['actions']:\n        if action['kind']=='add': pending.append(action['id'])\n        elif action['kind']=='rollback': pending.clear()\n        elif action['kind']=='commit': stored.extend(pending); pending.clear()\n    return {'stored':stored,'pending':pending}",
          [({"stored": [], "actions": [{"kind": "add", "id": 1}, {"kind": "flush"}]}, {"stored": [], "pending": [1]})], [({"stored": [1], "actions": [{"kind": "add", "id": 2}, {"kind": "rollback"}, {"kind": "commit"}]}, {"stored": [1], "pending": []}), ({"stored": [], "actions": [{"kind": "add", "id": 3}, {"kind": "commit"}]}, {"stored": [3], "pending": []})], ["User", "None"], phase=3),
    topic("backend.relationships", "Связь: внешний ключ и связанные объекты", ["backend.sqlalchemy_orm"],
          "ForeignKey связывает столбцы и ограничивает допустимые значения, а relationship описывает навигацию ORM между объектами. Один пользователь может иметь много заказов. Отсутствие связанных объектов не означает отсутствие пользователя; lazy-loading может дополнительно обращаться к БД.",
          "users = [1, 2]\norders = [{'user_id':1,'id':8}]\nprint({u:[o['id'] for o in orders if o['user_id']==u] for u in users})", "{1: [8], 2: []}",
          "Что выражает relationship в ORM?", ["Навигацию между связанными объектами", "Только пароль соединения", "Автоматическую публикацию данных в API"],
          ["Связь объектов строится поверх схемы и ключей.", "Учетные данные не описывают отношение таблиц.", "Response model и права API определяются отдельно."],
          "solve(payload) получает users:[{id}],orders:[{id,user_id}]. Верните список {'id':user_id,'order_ids':[...]} в порядке users, order_ids отсортированы. Заказы неизвестного пользователя не включайте; у пользователя без заказов список пуст.",
          "def solve(payload): return [{'id':u['id'],'order_ids':sorted(o['id'] for o in payload['orders'] if o['user_id']==u['id'])} for u in payload['users']]",
          [({"users": [{"id": 1}, {"id": 2}], "orders": [{"id": 8, "user_id": 1}]}, [{"id": 1, "order_ids": [8]}, {"id": 2, "order_ids": []}])], [({"users": [], "orders": [{"id": 9, "user_id": 2}]}, []), ({"users": [{"id": 1}], "orders": [{"id": 3, "user_id": 1}, {"id": 2, "user_id": 1}]}, [{"id": 1, "order_ids": [2, 3]}])], ["{1: [8]}", "{1: [], 2: [8]}"], phase=3),
    topic("backend.n_plus_one", "N+1: число запросов растёт с коллекцией", ["backend.relationships"],
          "N+1 возникает, когда один запрос получает список объектов, а каждый lazy relationship запускает отдельный запрос. Загрузить связи пакетом через selectinload или подходящий join часто полезнее. Проверяют число запросов и реальный план; один гигантский join не всегда лучший вариант.",
          "users = 3\nprint(1 + users)\nprint(2)", "4\n2",
          "Как уменьшить N+1 при загрузке заказов списка пользователей?", ["Загрузить нужные связи пакетом, например selectinload", "Повторить тот же запрос для каждого пользователя", "Добавить sleep между запросами"],
          ["Пакетная загрузка ограничивает число дополнительных запросов.", "Это сохраняет проблему линейного роста запросов.", "Задержка не уменьшает количество обращений к БД."],
          "solve(payload) получает users — список id, orders — записи {user_id,id}. Один раз сгруппируйте orders по user_id и верните список списков order id для каждого users в том же порядке. id заказов сортируйте. Повторный user id должен получить тот же набор, неизвестный — [].",
          "def solve(payload):\n    grouped={}\n    for order in payload['orders']: grouped.setdefault(order['user_id'],[]).append(order['id'])\n    for values in grouped.values(): values.sort()\n    return [grouped.get(user,[]) for user in payload['users']]",
          [({"users": [1, 2], "orders": [{"user_id": 1, "id": 8}]}, [[8], []])], [({"users": [1, 1, 9], "orders": [{"user_id": 1, "id": 2}, {"user_id": 1, "id": 1}]}, [[1, 2], [1, 2], []]), ({"users": [], "orders": []}, [])], ["3\n2", "4\n4"], phase=3),
    topic("backend.connection_pooling", "Пул соединений: ограниченный ресурс", ["backend.n_plus_one"],
          "Пул повторно использует соединения и ограничивает их число. Соединение нужно возвращать после работы; держать его во время долгого внешнего ожидания увеличивает конкуренцию. Таймаут ожидания пула не равен таймауту SQL-запроса.",
          "pool_size, overflow = 5, 2\nprint(pool_size + overflow)", "7",
          "Что происходит при исчерпании ограниченного пула?", ["Запрос ждёт освобождения или получает ошибку по таймауту ожидания", "Неограниченно создаются новые соединения", "Все существующие данные удаляются"],
          ["Ограничение защищает БД и приложение от бесконтрольного роста.", "Настроенный предел нельзя считать неограниченным.", "Пул управляет соединениями, а не удалением данных."],
          "solve(payload) получает capacity>=0 и actions из 'acquire'/'release'. Моделируйте пул: acquire при used<capacity увеличивает used и добавляет true, иначе false; release уменьшает used до минимум 0, результата не добавляет. Верните {'accepted':[bool...],'used':int}.",
          "def solve(payload):\n    used=0; accepted=[]\n    for action in payload['actions']:\n        if action=='acquire':\n            ok=used<payload['capacity']; accepted.append(ok); used+=int(ok)\n        else: used=max(0,used-1)\n    return {'accepted':accepted,'used':used}",
          [({"capacity": 1, "actions": ["acquire", "acquire", "release", "acquire"]}, {"accepted": [True, False, True], "used": 1})], [({"capacity": 0, "actions": ["release", "acquire"]}, {"accepted": [False], "used": 0}), ({"capacity": 2, "actions": []}, {"accepted": [], "used": 0})], ["5", "2"], phase=3),
    topic("backend.caching", "Кэш: попадание, истечение и инвалидация", ["backend.connection_pooling"],
          "Кэш хранит копию результата для ускорения повторных чтений. Ключ должен учитывать параметры и область доступа; неверный ключ может вернуть данные другого пользователя. TTL ограничивает срок хранения, но обновления исходных данных могут требовать инвалидации раньше.",
          "cache = {'value': 0, 'expires_at': 10}\nprint(cache['value'] if 9 < cache['expires_at'] else None)", "0",
          "Можно ли считать 0 отсутствующим значением в кэше?", ["Нет: 0 может быть корректным сохранённым результатом", "Да: всякое ложное значение означает miss", "Да: кэш хранит только непустые строки"],
          ["Попадание определяется наличием и сроком, а не truthiness значения.", "False, 0 и пустая строка могут быть валидными данными.", "Кэш может хранить разные типы значений."],
          "solve(payload) получает cache:key->{value,expires_at},key,now. Верните {'hit':true,'value':value} если запись есть и now<expires_at; иначе {'hit':false,'value':null}. Ноль, false и пустая строка — допустимые значения.",
          "def solve(payload):\n    row=payload['cache'].get(payload['key'])\n    if row is not None and payload['now']<row['expires_at']: return {'hit':True,'value':row['value']}\n    return {'hit':False,'value':None}",
          [({"cache": {"x": {"value": 0, "expires_at": 10}}, "key": "x", "now": 9}, {"hit": True, "value": 0})], [({"cache": {"x": {"value": False, "expires_at": 10}}, "key": "x", "now": 10}, {"hit": False, "value": None}), ({"cache": {}, "key": "x", "now": 0}, {"hit": False, "value": None})], ["None", "10"], phase=3),
    topic("backend.redis_basics", "Redis: ключ, тип и время жизни", ["backend.caching"],
          "Redis хранит данные по ключу и поддерживает разные типы. TTL возвращает оставшееся время; в Redis -1 означает ключ без истечения, -2 — отсутствующий ключ. Redis может служить кэшем или частью очереди, но долговечность зависит от конфигурации и выбранного протокола.",
          "def ttl(exists, expires_at, now):\n    if not exists: return -2\n    if expires_at is None: return -1\n    return max(0, expires_at-now)\nprint(ttl(True, None, 5), ttl(False, None, 5))", "-1 -2",
          "Что означает TTL=-1 для существующего ключа?", ["У ключа нет установленного срока истечения", "Ключ не существует", "Ключ просрочен одну секунду назад"],
          ["Отсутствующий ключ обозначается другим результатом -2.", "Это значение -2, а не -1.", "Отрицательные служебные значения не являются длительностью просрочки."],
          "solve(payload) получает exists,expires_at (int/null),now. Верните -2 если ключ отсутствует или expires_at<=now; -1 если существующий ключ не имеет срока; иначе expires_at-now. Это модель TTL в целых секундах без подключения к Redis.",
          "def solve(payload):\n    if not payload['exists']: return -2\n    expiry=payload['expires_at']\n    if expiry is None: return -1\n    return expiry-payload['now'] if expiry>payload['now'] else -2",
          [({"exists": True, "expires_at": 10, "now": 7}, 3)], [({"exists": True, "expires_at": None, "now": 7}, -1), ({"exists": True, "expires_at": 7, "now": 7}, -2), ({"exists": False, "expires_at": 10, "now": 0}, -2)], ["-2 -1", "0 0"], phase=3),
    topic("backend.docker_basics", "Контейнер: образ и конфигурация запуска", ["backend.redis_basics"],
          "Образ задаёт содержимое контейнера, а запуск добавляет ограничения, сеть и mounts. Non-root, read-only filesystem и отсутствие секретов уменьшают риск, но сам контейнер не гарантирует изоляцию недоверенного кода. Образ лучше фиксировать по digest для воспроизводимости.",
          "config = {'user':'10001','read_only':True,'network':'none'}\nprint(config['user'] != '0' and config['read_only'])", "True",
          "Гарантирует ли одно наличие контейнера безопасный запуск чужого кода?", ["Нет: нужны проверенные ограничения и границы изоляции", "Да: любой Docker-контейнер является полной гарантией", "Да: если контейнер работает от root"],
          ["Сеть, привилегии, mounts и лимиты меняют риск.", "Контейнер не отменяет ошибки конфигурации и ядра.", "Root и дополнительные привилегии увеличивают риск."],
          "solve(payload) получает config с user,read_only,network,privileged. Верните отсортированный список нарушений: 'root' для user='0' или 'root'; 'writable' если read_only=false; 'network' если network!='none'; 'privileged' если privileged=true. Это проверка заданной политики, не аттестация изоляции.",
          "def solve(payload):\n    c=payload['config']; errors=[]\n    if c['user'] in {'0','root'}: errors.append('root')\n    if not c['read_only']: errors.append('writable')\n    if c['network']!='none': errors.append('network')\n    if c['privileged']: errors.append('privileged')\n    return sorted(errors)",
          [({"config": {"user": "10001", "read_only": True, "network": "none", "privileged": False}}, [])], [({"config": {"user": "root", "read_only": False, "network": "bridge", "privileged": True}}, ["network", "privileged", "root", "writable"])], ["False", "0"], phase=3),
    topic("backend.linux_cli", "CLI: аргументы и shell", ["backend.docker_basics"],
          "Команда запускается с программой и аргументами. subprocess с argv и shell=False не интерпретирует пользовательский аргумент как shell-код. Конкатенация строки для shell опасна. Даже без shell нужно проверять разрешённую программу, пути и лимиты.",
          "import shlex\nprint(shlex.split('python -m app --name \"hello world\"'))", "['python', '-m', 'app', '--name', 'hello world']",
          "Как передать недоверенный текст как один аргумент без shell-интерпретации?", ["Использовать список argv и shell=False", "Склеить строку и включить shell=True", "Выполнить текст как Python-код"],
          ["Граница аргументов отделяется от языка shell.", "Shell может интерпретировать подстановки и операторы.", "exec превращает данные в исполняемый код."],
          "solve(payload) получает script и name. Верните argv ['python',script,'--name',name], сохранив name одним аргументом даже при пробелах, ';' или '$()'. Ничего не исполняйте.",
          "def solve(payload): return ['python',payload['script'],'--name',payload['name']]",
          [({"script": "app.py", "name": "hello world"}, ["python", "app.py", "--name", "hello world"])], [({"script": "app.py", "name": "a; $(echo x)"}, ["python", "app.py", "--name", "a; $(echo x)"]), ({"script": "x.py", "name": ""}, ["python", "x.py", "--name", ""])], ["['python', '-m', 'app', '--name', 'hello', 'world']", "['python -m app']"], phase=3),
    topic("backend.git_basics", "Git: рабочее дерево, индекс и commit", ["backend.linux_cli"],
          "Рабочее дерево содержит текущие файлы; индекс хранит подготовленный снимок следующего commit. git add обновляет индекс, commit записывает его. Изменение файла после add не попадает в commit автоматически; секреты не должны попадать ни в индекс, ни в историю.",
          "working = 'v1'\nstaged = working\nworking = 'v2'\nprint(staged, working)", "v1 v2",
          "Что попадает в commit после изменения файла уже после git add?", ["Подготовленная в индексе версия до нового add", "Всегда последнее содержимое рабочего дерева", "Все файлы на компьютере"],
          ["Commit использует индекс, а не произвольные текущие файлы.", "Новый вариант нужно снова добавить в индекс.", "Git работает с выбранным репозиторием."],
          "solve(payload) получает working — словарь file->content и actions. Действие add с path копирует текущий working[path] в staged; edit с path/content меняет working; commit копирует staged в history. Верните {'working':..., 'staged':..., 'history':список снимков}. Все добавляемые пути существуют.",
          "def solve(payload):\n    working=dict(payload['working']); staged={}; history=[]\n    for a in payload['actions']:\n        if a['kind']=='add': staged[a['path']]=working[a['path']]\n        elif a['kind']=='edit': working[a['path']]=a['content']\n        else: history.append(dict(staged))\n    return {'working':working,'staged':staged,'history':history}",
          [({"working": {"a": "v1"}, "actions": [{"kind": "add", "path": "a"}, {"kind": "edit", "path": "a", "content": "v2"}, {"kind": "commit"}]}, {"working": {"a": "v2"}, "staged": {"a": "v1"}, "history": [{"a": "v1"}]})], [({"working": {}, "actions": [{"kind": "commit"}]}, {"working": {}, "staged": {}, "history": [{}]})], ["v2 v2", "v1 v1"], phase=3),
    topic("backend.git_branching", "Ветка: ссылка на commit", ["backend.git_basics"],
          "Ветка Git — изменяемая ссылка на commit. Новая ветка начинается с существующего снимка и позволяет добавлять commits отдельно. Merge объединяет истории; при конфликте нужно решить содержимое, а не слепо выбрать любой вариант.",
          "branches = {'main':'a1'}\nbranches['feature'] = branches['main']\nbranches['feature'] = 'b2'\nprint(branches['main'], branches['feature'])", "a1 b2",
          "Что такое ветка Git?", ["Именованная ссылка на commit", "Обязательная отдельная копия всех файлов вне репозитория", "Только имя удалённого сервера"],
          ["Ветка указывает на вершину своей истории.", "Ветка не требует отдельной физической копии файлов.", "Remote и branch — разные сущности."],
          "solve(payload) получает parents:commit->parent/null и left/right commit ids. Верните ближайший общий предок: идите от left к корню, затем от right и выберите первый встреченный commit из левой цепочки. Истории ацикличны; если общего предка нет, верните null.",
          "def solve(payload):\n    seen=set(); node=payload['left']; parents=payload['parents']\n    while node is not None: seen.add(node); node=parents.get(node)\n    node=payload['right']\n    while node is not None:\n        if node in seen: return node\n        node=parents.get(node)\n    return None",
          [({"parents": {"a": None, "b": "a", "c": "a"}, "left": "b", "right": "c"}, "a")], [({"parents": {"a": None, "b": "a"}, "left": "b", "right": "b"}, "b"), ({"parents": {"a": None, "x": None}, "left": "a", "right": "x"}, None)], ["b2 b2", "a1 a1"], phase=3),
    topic("backend.ci_basics", "CI: автоматическая проверка изменений", ["backend.git_branching"],
          "CI запускает проверки при изменении кода в воспроизводимом окружении. Успешный lint не заменяет тесты, а успешные тесты не доказывают production-изоляцию. Публикация выполняется только после необходимых проверок; секреты CI ограничиваются нужными правами.",
          "checks = {'lint':True, 'tests':False, 'build':True}\nprint(all(checks.values()))", "False",
          "Когда допускается следующий этап после обязательных проверок?", ["Когда каждая обязательная проверка успешно завершена", "Когда прошла только первая проверка", "Когда проверок вообще нет, но название job красивое"],
          ["Gate должен учитывать весь обязательный набор.", "Остальные проверки могут обнаружить другую ошибку.", "Название job не является результатом проверки."],
          "solve(payload) получает required — список имён и results:name->'passed'/'failed'/'pending'. Верните bool допуска: все required присутствуют и имеют passed. Пустой required допустим и даёт true; дополнительные checks не влияют.",
          "def solve(payload): return all(payload['results'].get(name)=='passed' for name in payload['required'])",
          [({"required": ["lint", "tests"], "results": {"lint": "passed", "tests": "passed"}}, True)], [({"required": ["tests"], "results": {}}, False), ({"required": ["build"], "results": {"build": "pending"}}, False), ({"required": [], "results": {"other": "failed"}}, True)], ["True", "pending"], phase=3),
    topic("backend.ci_testing", "Тесты CI: поведение и регрессии", ["backend.ci_basics", "python.testing_basics"],
          "Тест должен проверять внешний результат или доменный инвариант, а не повторять строку реализации. Регрессия воспроизводит конкретный сбой, включая граничный вход. Unit, integration и E2E решают разные задачи; SQLite не доказывает PostgreSQL row locking.",
          "def divide(a,b): return None if b==0 else a/b\ncases = [(6,2,3),(5,0,None)]\nprint(all(divide(a,b)==expected for a,b,expected in cases))", "True",
          "Какой тест полезнее при исправлении ошибки на пустом входе?", ["Регрессия, вызывающая публичное поведение на пустом входе", "Проверка, что исходный текст содержит имя новой переменной", "Тест только на обычном непустом случае"],
          ["Такой тест доказывает устранение конкретного сбоя.", "Имя переменной не гарантирует правильный результат.", "Обычный случай мог работать и до исправления."],
          "solve(payload) получает cases — записи {actual,expected}. Верните {'passed':число точных равенств,'total':число случаев,'failed_indices':[индексы несовпадений]}. Индексы с нуля; пустой набор даёт нули и []. JSON-значения сравнивайте обычным равенством Python.",
          "def solve(payload):\n    failed=[i for i,c in enumerate(payload['cases']) if c['actual']!=c['expected']]\n    return {'passed':len(payload['cases'])-len(failed),'total':len(payload['cases']),'failed_indices':failed}",
          [({"cases": [{"actual": 1, "expected": 1}, {"actual": [], "expected": [1]}]}, {"passed": 1, "total": 2, "failed_indices": [1]})], [({"cases": []}, {"passed": 0, "total": 0, "failed_indices": []}), ({"cases": [{"actual": None, "expected": None}]}, {"passed": 1, "total": 1, "failed_indices": []})], ["False", "None"], phase=3),
    topic("backend.structured_logging", "Структурный лог: поля вместо разбора текста", ["backend.ci_testing"],
          "Структурные записи имеют стабильные поля event, level, request_id и безопасные данные. JSON сохраняет типы и упрощает поиск; произвольный текст пользователя остаётся значением, а не инструкцией. Поля с секретами исключаются по allowlist, а не через неполную замену строк.",
          "import json\nrecord = {'event':'request','status':200}\nprint(json.dumps(record, sort_keys=True))", '{"event": "request", "status": 200}',
          "Почему JSON-поле status полезнее числа внутри свободного текста?", ["Сохраняет отдельное типизированное поле для поиска и анализа", "Автоматически шифрует все данные", "Разрешает логировать пароли"],
          ["Анализатору не нужно угадывать значение из фразы.", "JSON сам по себе не является шифрованием.", "Формат не меняет требование исключать секреты."],
          "solve(payload) получает level,event,request_id. Верните JSON-строку только с этими тремя полями, sort_keys=True и ensure_ascii=False. level переведите в верхний регистр; остальные строки сохраняйте, включая кавычки и переносы.",
          "import json\ndef solve(payload): return json.dumps({'level':payload['level'].upper(),'event':payload['event'],'request_id':payload['request_id']},sort_keys=True,ensure_ascii=False)",
          [({"level": "info", "event": "login", "request_id": "r"}, '{"event": "login", "level": "INFO", "request_id": "r"}')], [({"level": "warn", "event": "вход", "request_id": ""}, '{"event": "вход", "level": "WARN", "request_id": ""}')], ['{"event": "request", "status": "200"}', "request 200"], phase=3),
    topic("backend.observability", "Наблюдаемость: метрики, логи и трассы", ["backend.structured_logging"],
          "Метрики показывают агрегаты, логи — события, трассы — путь запроса через операции. Нужно наблюдать latency, error rate и насыщение ресурсов. Перцентили нельзя заменять средним: несколько медленных запросов могут быть скрыты средним значением.",
          "durations = [1,1,1,97]\nprint(sum(durations)/len(durations))\nprint(max(durations))", "25.0\n97",
          "Что может скрыть средняя задержка?", ["Редкие очень медленные запросы", "Все успешные запросы автоматически", "Само наличие сервера"],
          ["Хвост распределения нужно смотреть отдельно.", "Успех измеряется по статусам, а не одному среднему.", "Latency описывает время операций."],
          "solve(payload) получает durations — неотрицательные числа и statuses — целые HTTP-коды такой же длины. Верните {'count':N,'errors':число status>=500,'max_ms':максимум либо0}. Не делайте вывод об успехе по одной latency.",
          "def solve(payload): return {'count':len(payload['durations']),'errors':sum(s>=500 for s in payload['statuses']),'max_ms':max(payload['durations'],default=0)}",
          [({"durations": [2, 90], "statuses": [200, 500]}, {"count": 2, "errors": 1, "max_ms": 90})], [({"durations": [], "statuses": []}, {"count": 0, "errors": 0, "max_ms": 0}), ({"durations": [0, 1], "statuses": [404, 503]}, {"count": 2, "errors": 1, "max_ms": 1})], ["97.0\n25", "1.0\n97"], phase=3),
    topic("backend.security_basics", "Граница доверия: вход, права и пути", ["backend.observability"],
          "Недоверенные данные валидируют на границе, действия проверяют по владельцу и правам, а секреты не возвращают клиенту. Allowlist уменьшает поверхность ввода, но не заменяет авторизацию. Для файловых путей нужно исключить traversal и символьные ссылки; строковая проверка — только один слой защиты.",
          "from pathlib import PurePosixPath\npath = PurePosixPath('../secret')\nprint('..' in path.parts)", "True",
          "Можно ли доверять user_id, переданному клиентом для доступа к данным?", ["Нет: владелец устанавливается сервером по проверенной сессии", "Да: если поле имеет красивое имя", "Да: если пользователь скрыл поле в форме"],
          ["Иначе прямой запрос может выбрать чужого владельца.", "Имя поля не подтверждает право на действие.", "Скрытое поле тоже контролируется клиентом."],
          "solve(payload) получает path — POSIX-строку. Верните false для пустой строки, абсолютного пути, любого сегмента '..', обратного слеша или NUL; иначе true. Это лексический allowlist учебного пути, а не доказательство отсутствия symlink на диске. Ничего не открывайте.",
          "from pathlib import PurePosixPath\ndef solve(payload):\n    path=payload['path']\n    return bool(path) and not path.startswith('/') and '..' not in PurePosixPath(path).parts and '\\\\' not in path and '\\x00' not in path",
          [({"path": "lessons/example.py"}, True)], [({"path": "../secret"}, False), ({"path": "/etc/passwd"}, False), ({"path": "a\\b"}, False), ({"path": ""}, False)], ["False", "secret"], phase=3),
]


def build_topic(row, ordinal):
    # Positions vary across the authored catalog; the API also randomizes within
    # the server-owned session without changing the immutable answer key.
    choices = list(row["choices"])
    correct = choices[0]
    explanations = dict(zip(choices, row["explanations"]))
    shift = ordinal % len(choices)
    choices = choices[shift:] + choices[:shift]
    lesson_id = row["lesson_id"]
    practice = row["practice"]
    lesson = {
        "id": lesson_id, "title": row["title"], "skill_id": row["skill"],
        "prerequisites": row["prerequisite"], "difficulty": 5 if row["skill"].startswith("python.") else 4,
        "minutes": row["minutes"], "goal": "Применить и объяснить: " + row["title"].lower() + ".",
        "theory": row["theory"], "example": row["example"], "example_output": row["output"],
        "checkpoint": {"prompt": row["question"], "choices": choices},
        "misconception_check": {"misconception": row["choices"][1], "prompt": "Объясните ошибку в этом утверждении и сформулируйте корректное правило."},
        "practice": practice, "conclusion": row["explanations"][0],
        "question": row["question"], "choices": choices, "answer": correct,
    }
    if row["phase"] is not None: lesson["phase"] = row["phase"]
    lesson["body"] = (f"Цель: {lesson['goal']}\nПеред началом: " + ", ".join(row["prerequisite"]) +
                      f"\n\nТеория: {row['theory']}\n\nCheckpoint: {row['question']}\n\nПрактика: {practice}\n\nВывод: {lesson['conclusion']}")
    prediction_choices = [row["output"], *row["output_distractors"]]
    prediction_shift = (ordinal + 1) % 3
    prediction_choices = prediction_choices[prediction_shift:] + prediction_choices[:prediction_shift]
    checks = (
        {"id": lesson_id + "-concept", "prompt": row["question"], "choices": choices,
         "answer": correct, "explanation": row["explanations"][0], "choice_explanations": explanations},
        {"id": lesson_id + "-trace", "prompt": "Предскажите полный вывод этого фрагмента:\n" + row["example"],
         "choices": prediction_choices, "answer": row["output"],
         "explanation": "Следуйте по строкам примера с учётом правила: " + row["explanations"][0],
         "choice_explanations": {
             row["output"]: "Это точный вывод фрагмента. " + row["explanations"][0],
             row["output_distractors"][0]: "Этот вариант не учитывает состояние или порядок вызовов примера. " + row["explanations"][1],
             row["output_distractors"][1]: "Этот вариант подменяет результат другого шага. " + row["explanations"][2],
         }},
    )
    ladder = {"version": 1, "lesson_id": lesson_id, "skill_id": row["skill"], "hints": (
        (1, "direction", "Разделите условие упражнения на входные данные, требуемый результат и граничный случай."),
        (2, "concept", "Прочитайте теорию о «" + row["title"] + "» и найдите правило, которое отличает пример от неверного варианта."),
        (3, "step", "Проследите один публичный вход вручную; затем отдельно проверьте нулевое, пустое или ошибочное значение, указанное в условии."),
        (4, "pseudocode", "прочитать payload\nприменить правило темы к данным\nпроверить граничный случай\nвернуть ровно требуемый формат"),
        (5, "solution", "Эталон практики:\n" + row["solution"]),
    )}
    return lesson, checks, ladder


COMPLETION_LESSONS = tuple(build_topic(row, i)[0] for i, row in enumerate(TOPICS))
COMPLETION_CHECKS = {row["lesson_id"]: build_topic(row, i)[1] for i, row in enumerate(TOPICS)}
COMPLETION_LADDERS = {row["lesson_id"]: build_topic(row, i)[2] for i, row in enumerate(TOPICS)}
COMPLETION_CODE_SPECS = {row["lesson_id"]: row for row in TOPICS}
